Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -112,3 +112,58 @@ jobs:
           git config user.email github-actions@github.com
           git add .
           git diff-index --quiet HEAD || (git commit -m "Update ${{ secrets.APP_NAME }} image tag to sha-${{ env.SHORT_SHA }}" && git push)
+
+          # Infra 저장소 업데이트 단계-2
+      - name: Build, tag, and push image to Amazon ECR
+        id: build-image-2
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          DOCKER_TAG: ${{ env.APP_ENV }}
+        run: |
+          docker build --build-arg VITE_API_BASE_URL=${{ secrets.SERVER_HOST_2 }} -t ${{ env.ECR_REPOSITORY }}:sha-${{ env.SHORT_SHA }}-main .
+          docker push ${{ env.ECR_REPOSITORY }}:sha-${{ env.SHORT_SHA }}-main
+
+      - name: Checkout infrastructure repository2
+        uses: actions/checkout@v3
+        with:
+          repository: TP1-OuterMSA/msa-infra-main
+          path: msa-infra-main
+          token: ${{ secrets.GH_PAT_2 }}
+
+      - name: Debug directory structure
+        run: |
+          cd msa-infra-main
+          ls -la
+          echo "Checking charts directory:"
+          ls -la charts/
+          echo "Checking services directory:"
+          ls -la charts/services/ || echo "Services directory not found"
+          find . -name "init-page" -type d
+
+      - name: Update image tag in Helm chart
+        run: |
+          cd msa-infra-main/charts/services/${{ env.APP_NAME_2 }}
+          
+          if [ -f values.yaml ]; then
+            echo "values.yaml exists"
+            cat values.yaml | head -10  # 파일 내용 일부 출력
+          fi
+          OLD_TAG=$(grep -oP 'tag: "\K[^"]+' values.yaml)
+          sed -i "s/tag: \".*\"/tag: \"sha-${{ env.SHORT_SHA }}-main\"/g" values.yaml
+          echo "Updated values.yaml content:"
+          cat values.yaml
+          if [ "$OLD_TAG" != "sha-${{ env.SHORT_SHA }}" ]; then
+            echo "TAG_CHANGED=true" >> $GITHUB_ENV
+            echo "OLD_TAG=$OLD_TAG" >> $GITHUB_ENV
+          else
+            echo "TAG_CHANGED=false" >> $GITHUB_ENV
+          fi
+
+      - name: Commit and push changes to infrastructure repo
+        run: |
+          cd msa-infra-main
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+          git add .
+          git diff-index --quiet HEAD || (git commit -m "Update ${{ env.APP_NAME_2 }} image tag to sha-${{ env.SHORT_SHA }}" && git push)
+          
